require 'netflix/errors'
require 'netflix/response'
require 'netflix/client'
require 'netflix/user'
require 'netflix/queue'
require 'netflix/disc'
require 'netflix/recommendation'
require 'netflix/recommendations_list'